# Script to deploy on the Render clod platform

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
        
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: 'https://api.render.com/deploy/srv-ciofmbenqqlfegd1bum0?key=7vF-N2jZnYI'
        webhook_secret: '7vF-N2jZnYI'
        
    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}} #This is the github token
        service-id: "srv-ciofmbenqqlfegd1bum0" #This id is unique for each app
        retires: 20
        wait: 16000
        sleep: 30000
  
